"""OFARM Python SDK candidate shape v0.1.

Implementation/conformance support only. Methods intentionally describe the public shape without implementing transport.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class RuntimeProblem:
    reason_code: str
    severity: str
    title: str
    detail: Optional[str] = None
    trace_ref: Optional[str] = None


@dataclass(frozen=True)
class QualifiedResult:
    data: Any
    qualification: Dict[str, Any]
    problems: List[RuntimeProblem]


class OFARMClient:
    def capabilities_get(self) -> QualifiedResult: ...
    def authority_preflight(self, request: Dict[str, Any]) -> QualifiedResult: ...
    def commits_dry_run(self, request: Dict[str, Any]) -> QualifiedResult: ...
    def commits_submit(self, request: Dict[str, Any], *, idempotency_key: str, human_approval_ref: Optional[str] = None) -> QualifiedResult: ...
    def evidence_register(self, request: Dict[str, Any], *, idempotency_key: Optional[str] = None) -> QualifiedResult: ...
    def queries_plan(self, request: Dict[str, Any]) -> QualifiedResult: ...
    def queries_execute(self, request: Dict[str, Any]) -> QualifiedResult: ...
    def materializations_get(self, scope: str, *, require_freshness: bool = False) -> QualifiedResult: ...
    def assemblies_dry_run(self, request: Dict[str, Any]) -> QualifiedResult: ...
    def assemblies_create(self, request: Dict[str, Any], *, idempotency_key: str, human_approval_ref: Optional[str] = None) -> QualifiedResult: ...
    def identity_resolve(self, request: Dict[str, Any]) -> QualifiedResult: ...
    def imports_submit_candidate(self, request: Dict[str, Any], *, idempotency_key: str) -> QualifiedResult: ...
    def imports_loss_map(self, import_receipt_ref: str) -> QualifiedResult: ...
    def sync_replay(self, request: Dict[str, Any], *, idempotency_key: str) -> QualifiedResult: ...
    def calculations_preview(self, request: Dict[str, Any]) -> QualifiedResult: ...
    def traces_get(self, trace_type: str, trace_id: str) -> QualifiedResult: ...


# Intentionally absent:
# save_canonical_assertion
# update_materialization_store
# mark_accepted_execution
# promote_advisory_output_to_compliance_fact
# generic_crud_client_for_truth_objects
